import { HeadCell } from './../../models/head-cell.model';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-to-do',
  templateUrl: './to-do.component.html',
  styleUrls: ['./to-do.component.scss']
})
export class ToDoComponent implements OnInit {

  constructor() { }

  headCells = [
    'teste1',
    'teste2',
    'teste2',
    'teste2',
    'teste2',
    'teste2',
    'teste3',
    'Actions'
  ]

  data: Array<any> = [
    {
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    }, {
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    }, {
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    }, {
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    }, {
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    }, {
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },{
      id: 1,
      teste1: 'teste1',
      teste2: 'teste2',
      teste3: 'teste2',
      teste4: 'teste2',
      teste5: 'teste2',
      teste6: 'teste2',
      teste7: 'teste2',
      teste8: 'teste2',
      teste9: 'teste2',
      teste0: 'teste2',
    },
  ]


  log(t: any) {
    console.log(t)
  }

  ngOnInit(): void {
  }

}
